2022-07-06 16:44:09,796:ERROR:Tried to divide by zero
Traceback (most recent call last):
  File "C:\Users\EESSAMMB\source\repos\PythonForDataScience\PythonForDataScience\logg.py", line 39, in divide
    result = x / y
ZeroDivisionError: division by zero
